# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Burger Rebellion - A food truck in downtown Sarnia
email: info@burgerrebellion.ca
description: > # this means to ignore newlines until "baseurl:"
  We're grillers, not fighters. Our mission is in the name of a tasty meal. A revolution for the taste buds, an insurrection against the barons of mediocrity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.burgerrebellion.ca" # the base hostname & protocol for your site
twitter_username: brgrrebellion
github_username:  storyboardinc

# Build settings
markdown: kramdown
